import jwt from "jsonwebtoken";

function getSecret(): string {
  const secret = process.env.JWT_SECRET;
  if (!secret) {
    throw new Error("JWT_SECRET is required");
  }
  return secret;
}

export interface JwtPayload {
  githubId: number;
  login: string;
  avatarUrl: string;
}

/**
 * One algorithm, named on both sides.
 *
 * Neither call stated one, which left the accepted set to whatever the library
 * infers from the key. That inference is the thing every JWT algorithm-confusion
 * bug has gone through, and it is a property of a dependency rather than of this
 * file — so it can change under us in a patch release. This app issues exactly
 * one kind of token, with a symmetric secret, and can say so.
 */
const ALGORITHM = "HS256" as const;

export function signToken(payload: JwtPayload): string {
  return jwt.sign(payload, getSecret(), { algorithm: ALGORITHM, expiresIn: "8h" });
}

export function verifyToken(token: string): JwtPayload {
  return jwt.verify(token, getSecret(), { algorithms: [ALGORITHM] }) as JwtPayload;
}

/**
 * A session lifted out of a request so it can outlive the key that signed it.
 *
 * `JWT_SECRET` is read from the AWS account's secret, so it changes when the
 * operator switches accounts in the desktop app. The session is the person's,
 * not the account's — being in `aws-guardrail-admins` is worth knowing in every
 * account — so it is captured before the switch and re-signed after it.
 */
export interface CarriedSession {
  payload: JwtPayload;
  /** The original expiry, in epoch seconds. Carried, never recomputed. */
  expiresAt: number;
}

/**
 * Read a still-valid session out of an Authorization header.
 *
 * Must be called *before* the new account's secrets load, which is the last
 * moment the key that signed it is in the process.
 *
 * Null for anything that is not a live session this app issued — no header, a
 * header of another kind, a forgery, or a token that has already expired.
 * Switching accounts must not be a way to renew a dead session, and switching
 * while signed out has to keep working: it is how AWS gets connected in the
 * first place, before there are any GitHub secrets to authenticate against.
 */
export function captureSession(header: string | undefined): CarriedSession | null {
  if (!header?.startsWith("Bearer ")) return null;
  try {
    const decoded = jwt.verify(header.slice(7), getSecret(), { algorithms: [ALGORITHM] }) as
      JwtPayload & { exp?: number };
    if (!decoded?.login || !decoded.exp) return null;
    return {
      payload: { githubId: decoded.githubId, login: decoded.login, avatarUrl: decoded.avatarUrl },
      expiresAt: decoded.exp,
    };
  } catch {
    // Expired, forged, or signed with a key this process no longer holds. All
    // three mean the same thing here: there is no session to carry.
    return null;
  }
}

/**
 * Re-sign a carried session with whichever key is loaded now.
 *
 * The expiry is the original one rather than a fresh eight hours. Carrying a
 * session across a switch is not a reason to be signed in for longer, and a
 * switch every few minutes would otherwise be a session that never ends.
 *
 * Null when the carried session expired between capture and re-issue, or when
 * no key is loaded at all — the account being switched *to* may hold no GitHub
 * secrets, in which case a random one is generated by the caller before this
 * runs.
 */
export function reissueSession(session: CarriedSession): string | null {
  const remaining = session.expiresAt - Math.floor(Date.now() / 1000);
  if (remaining <= 0) return null;
  try {
    return jwt.sign(session.payload, getSecret(), { algorithm: ALGORITHM, expiresIn: remaining });
  } catch {
    return null;
  }
}
